name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    #- name: Add conda to system path
    #  run: |
    #    # $CONDA is an environment variable pointing to the root of the miniconda directory
    #    echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get install graphviz
    - name: Train NN and compute confusion matrix
      run: |
        cd src
        python3 proyecto3_train.py -n 3 -t C
        python proyecto3_evaluate.py -i ../data/one.bmp
        python proyecto3_confusionMatrix.py
